### ISSUE TITLE
Test 3.2.1-B: New test for PreferContainedDescriptions

### ISSUE THREAD

**Issue by awoods** [fcrepo4-labs/Fedora-API-Test-Suite#101]
As a corollary to the `additionalValuesForPreferHeader` test for `PreferInboundReferences`
https://github.com/fcrepo4-labs/Fedora-API-Test-Suite/blob/master/src/main/java/org/fcrepo/spec/testsuite/crud/HttpGet.java#L61

...another test should be added to verify `PreferContainedDescriptions` : `MAY`

**Comment by zimeon** [comment]
:+1: - thanks for writing this up... I thought to when working on #97 but then forgot
