### ISSUE TITLE
I see failed results that don't appear to be failures 

### ISSUE THREAD

**Issue by dbernstein** [fcrepo4-labs/Fedora-API-Test-Suite#19]
I just downloaded and ran the tool against the latest fcrepo4 (f7aaf91e1). 

There were 35 passes and 13 failures. Looking at the results in Fedora-API-Test-Suite/test-output/emailable-report.html, I began parsing the failures.   Picking one from the list of 13 failures,  I examined the results of  httpHeadResponseHeadersSameAsHttpGet.  According the headers that were recorded in the response, it appears that the test is failing where it should be succeeding.   For example from the "Exception" section (accessed by clicking on the link with the name of the test, i.e. httpHeadResponseHeadersSameAsHttpGet) I can see that the test suite is complaining: 

Expected header "Link" was not "<http://www.w3.org/ns/ldp#Resource>;rel=\"type\"", was "<http://localhost:8080/static/constraints/ContainerConstraints.rdf>; rel="http://www.w3.org/ns/ldp#constrainedBy"". Headers are:
Date=Tue, 09 Jan 2018 08:22:38 GMT
ETag=W/"ddcf6f3e6cc12674c6bf10bb101f124cf72a271b"
Last-Modified=Tue, 09 Jan 2018 08:22:38 GMT
Link=<http://www.w3.org/ns/ldp#Resource>;rel="type"
Link=<http://www.w3.org/ns/ldp#Container>;rel="type"
Link=<http://www.w3.org/ns/ldp#BasicContainer>;rel="type"
Link=<http://localhost:8080/static/constraints/ContainerConstraints.rdf>; rel="http://www.w3.org/ns/ldp#constrainedBy"
Accept-Patch=application/sparql-update
Accept-Post=text/turtle,text/rdf+n3,text/n3,application/rdf+xml,application/n-triples,application/ld+json,multipart/form-data,application/sparql-update,message/external-body; access-type=URL
Allow=MOVE,COPY,DELETE,POST,HEAD,GET,PUT,PATCH,OPTIONS
Content-Type=text/turtle;charset=utf-8
Content-Length=0
Server=Jetty(9.2.3.v20140905)

But if you look at the headers, you can see clearly that Link=<http://www.w3.org/ns/ldp#Resource>;rel="type"  is present in the results.

**Comment by ibr-jabrego** [comment]
I reviewed this case and the test httpHeadResponseHeadersSameAsHttpGet was fixed. It is currently failing because the headers do not match as explained in the following Issue/Question.

https://github.com/fcrepo4-labs/Fedora-API-Test-Suite/issues/36
