### ISSUE TITLE
Create help message showing correct invocation

### ISSUE THREAD

**Issue by sprater** [fcrepo4-labs/Fedora-API-Test-Suite#34]
Create a usage() method to display program invocation information when program is called with the "help" flag or is called incorrectly.

**Comment by awoods** [comment]
@sprater : Is this still an issue? Options are currently printed to the terminal when incorrect (or `help`) options are provided. 
If you believe additional, specific information would be helpful, could you please add an example of such text here?

**Comment by sprater** [comment]
The options as they now display are fine.  This issue can be closed.
