### ISSUE TITLE
Root container for the fedora test suite

### ISSUE THREAD

**Issue by ibr-jabrego** [fcrepo4-labs/Fedora-API-Test-Suite#35]
Before the tests are run, the test suite creates a base container named testsuitecontainer concatenated with a timestamp. All following test requests are made to this folder. Currently, this LDPC is created with a simple POST.

Currently using Fedora API 5.0.0 to run the test suite.

POST /
Host: http://localhost:8080/fcrepo5/rest/
Slug: testsuitecontainer123456

However, when running the tests suite against other LDP servers like Cavendish and Trilpy the response from the request is a 400 Bad Request. Is the request missing some headers that the Fedora API is adding as default?

I tried a sample request from the LDP Primer
https://www.w3.org/2012/ldp/hg/ldp-primer/ldp-primer.html#meta-structure

EXAMPLE 6: Request - creating a new container

POST /
Host: http://localhost:8080/fcrepo5/rest/
Slug: testsuitecontainer123456
Content-Type: text/turtle
Link: <http://www.w3.org/ns/ldp/BasicContainer>; rel="type"

The response is a 400 Bad Request.

**Comment by escowles** [comment]
I was able to create a basic container with curl:
```
curl -i -X POST -H "Slug: test1234" -H "Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel=\"type\"" -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest
```

So I think the problem is with the Link header, which needs brackets around the URL and a `#` separating the namespace from the type.

**Comment by ibr-jabrego** [comment]
Thank you @escowles, that was the solution. I will make the changes to the Fedora Test Suite.
