### ISSUE TITLE
Creating Resource in direct container for prefer header test

### ISSUE THREAD

**Issue by ibr-jabrego** [fcrepo4-labs/Fedora-API-Test-Suite#38]
When creating the resource within a direct container, the Fedora API server returns a 400 Bad Request. Checked the server and it displayed a "Invalid interaction model: http://www.w3.org/ns/ldp#Resource. " Removed the Link geader and made the request. The resource was created with the following links.

Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Link: <http://www.w3.org/ns/ldp#Container>;rel="type"
Link: <http://www.w3.org/ns/ldp#DirectContainer>;rel="type"

Not sure if this is a bug or my request is missing something. Using section 3 from the LDP Primer as a sample, it only uses one link type.
https://www.w3.org/2012/ldp/hg/ldp-primer/ldp-primer.html#bugtracker

Steps Taken
 
1)Create Direct Container

POST http://localhost:8080/fcrepo5/rest/
Content-Type: text/turtle
Link: <http://www.w3.org/ns/ldp#DirectContainer>; rel="type";
Slug: DirectContainer

Body:

@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix bt: <http://example.org/vocab/bugtracker#> .

<> a ldp:DirectContainer;
  ldp:membershipResource <#it>;
  ldp:hasMemberRelation bt:hasBug;
  dcterms:title 'Product description of the LDP Demo product which is also an LDP-DC' .

2)Create Resource in DirectContainer (Bug)

POST http://localhost:8080/fcrepo5/rest/DirectContainer
Content-Type: text/turtle
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type";
Slug: Bug1

**Comment by awoods** [comment]
The Fedora/Modeshape implementation does not support the creation of LDPRs... I believe the LDP Specification allows for such behavior:
https://www.w3.org/TR/ldp/#ldpc-post-createrdf

**Comment by sprater** [comment]
@awoods :  can this ticket be closed as "won't fix" (not supported)?

**Comment by ibr-jabrego** [comment]
Yes, if it is not supported we will use a different type of Resource for the Direct Container. Thank you @awoods  and @sprater.
