### ISSUE TITLE
Links in Test Suite Report are incorrect

### ISSUE THREAD

**Issue by bseeger** [fcrepo4-labs/Fedora-API-Test-Suite#40]
The links in the test summary report that link back to sections the specification document are incorrect.   Not sure if it's all of them, but everyone I clicked on only took me to the top of the spec document. 

There's a very good chance they were correct at one point and are maybe out of date now. They need to be synched up again.

**Comment by randalldfloyd** [comment]
For reference, the mappings of links to specification anchors is implemented here:
https://github.com/fcrepo4-labs/Fedora-API-Test-Suite/blob/master/src/main/java/com/ibr/fedora/TestsLabels.java

**Comment by sprater** [comment]
Fixed in PR #44
