### ISSUE TITLE
Have a way to run only MUST tests (or SHOULD)

### ISSUE THREAD

**Issue by zimeon** [fcrepo4-labs/Fedora-API-Test-Suite#42]
Perhaps this is a subset of functionality required for #32, but it would be really nice to be able to limit the set of tests run to just those that are required by the specification (MUST), or expand to those recommended (MUST+SHOULD), or the current state which includes tests of MUST+SHOULD+MAY clauses. This would allow implementers to focus on the most critical issues first and, technically, an implementation meeting all of the MUST cases is compliant so that is a very useful subset of the whole test suite.

(I did look at the [earl spec](https://www.w3.org/TR/EARL10-Schema/) to see whether it had a standard way of marking tests according to rfc2119 for suitable post-processing -- earl doesn't though it is extensible so such information could be added. However, it is probably best to simply run a subset of test because that will be quicker.)

**Comment by sprater** [comment]
This is a good idea, and perhaps could be set up using testng annotations to group the tests.

**Comment by awoods** [comment]
I agree that this would be an excellent improvement. @sprater, do you have clear thoughts on an annotation approach? @randalldfloyd, is anything coming to mind?

**Comment by randalldfloyd** [comment]
@awoods Of course I'm still a fresh newbie sprinter and don't know the test suite code at all but it looks like TestNg has good support for group annotations and ability to override default group behaviors at runtime with the typical tools (maven etc.) What I don't know is what changes would be needed to allow for passing those group directives when running the standalone test suite jar.
