### ISSUE TITLE
Realign section 3.5 test labels to match current specification draft

### ISSUE THREAD

**Issue by randalldfloyd** [fcrepo4-labs/Fedora-API-Test-Suite#48]
Just need some minor editing of test labels to account for some labeling drift in the spec:

3.5-C appears to have been moved down into 3.5.1.  Labels should probably be shifted to reflect this as 3.5.1-A.

3.5-D appears to have been moved down into 3.5.1.  Labels should probably be shifted to reflect this as 3.5.1-B.

Since 3.5-C and D should be 3.5.1-A and 3.5.1-B, 3.5.1-A should be 3.5.1-C.

Since 3.5-C and D should be 3.5.1-A and 3.5.1-B, 3.5.1-B should be 3.5.1-D.

**Comment by sprater** [comment]
@randalldfloyd may I assign this task to you?

**Comment by randalldfloyd** [comment]
@sprater Yes I think I meant to do that on creation.

**Comment by sprater** [comment]
fixed in pull request #49
