### ISSUE TITLE
Test 3.2.1-A expects wrong Preference-Applied response

### ISSUE THREAD

**Issue by zimeon** [fcrepo4-labs/Fedora-API-Test-Suite#50]
[Test 3.2.1-A](https://github.com/fcrepo4-labs/Fedora-API-Test-Suite/blob/master/src/main/java/com/ibr/fedora/testsuite/HttpGet.java#L95) seems to want to see the URI `http://fedora.info/definitions/fcrepo#PreferInboundReferences` in the `Preference-Applied` header. I don't think the is right because the `Preference-Applied` is not expected to include data from `omit="..."` or `include="..."` but just the preference name which is `return=representation`. See, for example, [ex20/21 in LDP](https://www.w3.org/TR/ldp/#prefer-examples-direct-minimal-container-only1) and https://tools.ietf.org/html/rfc7240#section-3:

> The syntax of the Preference-Applied header differs from that of the Prefer header in that parameters are not included.

(I had this wrong in my test for `trilpy` too ;-) )

**Comment by zimeon** [comment]
Ah, I see the [Fedora 4 example](https://wiki.duraspace.org/display/FEDORA4x/RESTful+HTTP+API+-+Containers#RESTfulHTTPAPI-Containers-GETRetrievethecontentoftheresource) includes the parameter in the `Preference-Applied` response header -- I guess we could specify that but it goes against RFC7240 by my reading.  Will create Fedora API spec issue.

**Comment by zimeon** [comment]
Conclusion from [Fedora API discussion](https://github.com/fcrepo/fcrepo-specification/issues/349) is that test should check for a 
```
Preference-Applied: return=representation
```
response header (no parameters) to indicate that the preference was applied.

I think the test should also check the content to see that the preference was actually applied (from my reading it does not at the moment)

**Comment by sprater** [comment]
Thanks, @zimeon.  @ibr-jabrego is working on a similar fix to the 3.1.1 tests, I'll have him take a look at this, too.
